export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const POST_MESSAGE = 'POST_MESSAGE';
export const SELECT_CHANNEL = 'SELECT_CHANNEL';
export const RECEIVE_CABLE_MESSAGE = 'RECEIVE_CABLE_MESSAGE';
